spring:
  application:
    name: WordTrainer

  profiles:
    active:
      -prod

  datasource:
    url: jdbc:mysql://localhost:3306/wordtrainer?serverTimezone=Europe/Moscow
    username: wordtraineruser
    password: wordtrainerpwd-123

  jpa:
    hibernate:
      ddl-auto: 'update'
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

server:
  port: 9000

logging:
  level:
    org:
      hibernate:
        SQL: INFO


